/**
 * Generated by cxy
 */

// Base definitions
#define nullptr ((void *)0)
#define true  1
#define false  0
typedef int bool;
typedef unsigned int wchar_t;
typedef signed char int8_t;
typedef unsigned char uint8_t;
typedef signed short int16_t;
typedef unsigned short uint16_t;
typedef signed int int32_t;
typedef unsigned int uint32_t;
typedef signed long long int64_t;
typedef unsigned long long uint64_t;
typedef __int128_t int128_t;
typedef __uint128_t uint128_t;
#if defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wvisibility"
#pragma clang diagnostic ignored "-Wmain-return-type"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#pragma clang diagnostic ignored  "-Wincompatible-library-redeclaration"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wbuiltin-declaration-mismatch"
#pragma GCC diagnostic ignored "-Wincompatible-pointer-types"
#else
#error "Unsupported compiler"
#endif

#if __has_attribute(__builtin_unreachable)
#define unreachable(...)
    do {
        assert(!"Unreachable code reached");
        __builtin_unreachable();
    } while (0)
#else
#define unreachable(...) abort();
#endif

#define likely(x)      __builtin_expect(!!(x), 1)
#define unlikely(x)    __builtin_expect(!!(x), 0)

// Memory management flags
#define __CXY_LOOP_CLEANUP(FLAGS, LABEL) \
   if ((FLAGS) == 1) goto LABEL; \
   if ((FLAGS) == 2) { (FLAGS) = 0; break; }
#define __CXY_BLOCK_CLEANUP(FLAGS, LABEL) \
   if ((FLAGS) == 1) goto LABEL;
#define __CXY_DROP_WITH_FLAGS(FLAGS, ...) if (FLAGS) __VA_ARGS__

// Print int128/uint128 macros
#define INT128(h, l)     ((__int128_t)(((__uint128_t)(h) << 64) | (uint64_t)(l)) )
#define UINT128(h, l)    ((__uint128_t)(((__uint128_t)(h) << 64) | (uint64_t)(l)) )
